version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamisk53"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2kh2bm47pjr9"
s3_prefix = "dynamisk53"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
